In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("qoute_dataset.csv")
# Location of the dataset should be mentioned correctly

In [8]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [9]:
df.shape

(3038, 2)

# NLP Step

In [11]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [12]:
quotes = quotes.str.lower()

In [14]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [15]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [17]:
vocab_size = 10000

tokinizer = Tokenizer(num_words=vocab_size)
tokinizer.fit_on_texts(quotes)

In [18]:
word_index = tokinizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [19]:
sequence = tokinizer.texts_to_sequences(quotes)

In [20]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [21]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [22]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [23]:
len(X)

85271

In [24]:
len(y)

85271

In [25]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [27]:
y = np.array(y)

In [28]:
X_padded.shape

(85271, 745)

In [29]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [30]:
y.shape

(85271,)

In [31]:
y_one_hot.shape

(85271, 10000)

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense,GRU

In [33]:
embedding_dim = 50
rnn_units = 128

# RNN Model

In [34]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

In [35]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [36]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# LSTM Model

In [37]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [38]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [39]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
batch_size = 128
epochs = 100

In [35]:
history_rnn = rnn_model.fit(
    X_padded, y_one_hot,
    batch_size=batch_size,
    epochs=epochs,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 52s 78ms/step - accuracy: 0.0431 - loss: 6.7779 - val_accuracy: 0.0556 - val_loss: 6.5903
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.0697 - loss: 6.1935 - val_accuracy: 0.0860 - val_loss: 6.3975
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 70ms/step - accuracy: 0.0995 - loss: 5.8342 - val_accuracy: 0.1011 - val_loss: 6.2856
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.1166 - loss: 5.5323 - val_accuracy: 0.1081 - val_loss: 6.2831
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1291 - loss: 5.2651 - val_accuracy: 0.1103 - val_loss: 6.3317
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.1436 - loss: 5.0212 - val_accuracy: 0.1079 - val_loss: 6.3866
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1579 - loss: 4.7941 - val_accuracy: 0.1080 - val_loss: 6.4763
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1743 - loss: 4.5788 - val_accuracy: 0.1089 - val_loss: 6.5588
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1944 - loss: 4.3754 - val_accuracy: 0.1057 - val_loss: 6.6152
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.2161 - loss: 4.1787 - val_accuracy: 0.1020 - val_loss: 6.6990
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.2408 - loss: 3.9941 - val_accuracy: 0.1055 - val_loss: 6.7934
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.2634 - loss: 3.8224 - val_accuracy: 0.1034 - val_loss: 6.8714
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.2867 - loss: 3.6615 - val_accuracy: 0.1011 - val_loss: 6.9404
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.3089 - loss: 3.5145 - val_accuracy: 0.0949 - val_loss: 7.0548
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.3287 - loss: 3.3788 - val_accuracy: 0.1015 - val_loss: 7.1169
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.3479 - loss: 3.2536 - val_accuracy: 0.0960 - val_loss: 7.2219
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.3668 - loss: 3.1395 - val_accuracy: 0.0952 - val_loss: 7.2834
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.3828 - loss: 3.0309 - val_accuracy: 0.0959 - val_loss: 7.3804
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.4004 - loss: 2.9337 - val_accuracy: 0.0949 - val_loss: 7.4533
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.4158 - loss: 2.8376 - val_accuracy: 0.0920 - val_loss: 7.5329
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.4296 - loss: 2.7518 - val_accuracy: 0.0922 - val_loss: 7.6092
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 69ms/step - accuracy: 0.4438 - loss: 2.6712 - val_accuracy: 0.0917 - val_loss: 7.6751
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.4570 - loss: 2.5943 - val_accuracy: 0.0924 - val_loss: 7.7474
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.4713 - loss: 2.5217 - val_accuracy: 0.0919 - val_loss: 7.8057
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.4828 - loss: 2.4568 - val_accuracy: 0.0883 - val_loss: 7.9003
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.4932 - loss: 2.3916 - val_accuracy: 0.0875 - val_loss: 7.9497
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.5044 - loss: 2.3305 - val_accuracy: 0.0869 - val_loss: 8.0296
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.5153 - loss: 2.2767 - val_accuracy: 0.0870 - val_loss: 8.0914
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.5244 - loss: 2.2216 - val_accuracy: 0.0843 - val_loss: 8.1547
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.5336 - loss: 2.1707 - val_accuracy: 0.0810 - val_loss: 8.2091
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.5410 - loss: 2.1266 - val_accuracy: 0.0817 - val_loss: 8.2877
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.5512 - loss: 2.0809 - val_accuracy: 0.0840 - val_loss: 8.3481
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.5598 - loss: 2.0365 - val_accuracy: 0.0803 - val_loss: 8.4172
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.5678 - loss: 1.9985 - val_accuracy: 0.0810 - val_loss: 8.4732
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.5722 - loss: 1.9617 - val_accuracy: 0.0820 - val_loss: 8.5256
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.5802 - loss: 1.9235 - val_accuracy: 0.0800 - val_loss: 8.6181
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.5865 - loss: 1.8883 - val_accuracy: 0.0787 - val_loss: 8.6538
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.5922 - loss: 1.8569 - val_accuracy: 0.0776 - val_loss: 8.7117
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.5994 - loss: 1.8243 - val_accuracy: 0.0787 - val_loss: 8.7860
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6057 - loss: 1.7953 - val_accuracy: 0.0782 - val_loss: 8.8315
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.6100 - loss: 1.7666 - val_accuracy: 0.0799 - val_loss: 8.8997
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6143 - loss: 1.7395 - val_accuracy: 0.0792 - val_loss: 8.9557
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6203 - loss: 1.7115 - val_accuracy: 0.0775 - val_loss: 9.0024
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.6253 - loss: 1.6878 - val_accuracy: 0.0806 - val_loss: 9.0344
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.6305 - loss: 1.6655 - val_accuracy: 0.0766 - val_loss: 9.0790
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6346 - loss: 1.6420 - val_accuracy: 0.0729 - val_loss: 9.1701
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6371 - loss: 1.6199 - val_accuracy: 0.0768 - val_loss: 9.2442
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.6442 - loss: 1.5948 - val_accuracy: 0.0760 - val_loss: 9.2751
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.6471 - loss: 1.5781 - val_accuracy: 0.0765 - val_loss: 9.3048
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.6501 - loss: 1.5571 - val_accuracy: 0.0738 - val_loss: 9.3725
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6556 - loss: 1.5381 - val_accuracy: 0.0741 - val_loss: 9.4425
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.6573 - loss: 1.5176 - val_accuracy: 0.0715 - val_loss: 9.4657
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.6637 - loss: 1.4973 - val_accuracy: 0.0714 - val_loss: 9.5393
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.6646 - loss: 1.4873 - val_accuracy: 0.0748 - val_loss: 9.5666
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6686 - loss: 1.4661 - val_accuracy: 0.0739 - val_loss: 9.6537
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6707 - loss: 1.4556 - val_accuracy: 0.0726 - val_loss: 9.6838
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6739 - loss: 1.4384 - val_accuracy: 0.0693 - val_loss: 9.7099
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6769 - loss: 1.4215 - val_accuracy: 0.0765 - val_loss: 9.7878
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.6816 - loss: 1.4061 - val_accuracy: 0.0689 - val_loss: 9.8149
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6848 - loss: 1.3922 - val_accuracy: 0.0721 - val_loss: 9.8644
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6847 - loss: 1.3825 - val_accuracy: 0.0712 - val_loss: 9.9333
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6877 - loss: 1.3694 - val_accuracy: 0.0726 - val_loss: 9.9705
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6911 - loss: 1.3566 - val_accuracy: 0.0721 - val_loss: 9.9969
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6919 - loss: 1.3457 - val_accuracy: 0.0702 - val_loss: 10.0608
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.6941 - loss: 1.3330 - val_accuracy: 0.0678 - val_loss: 10.0928
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6982 - loss: 1.3181 - val_accuracy: 0.0704 - val_loss: 10.1382
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6994 - loss: 1.3076 - val_accuracy: 0.0691 - val_loss: 10.1499
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7022 - loss: 1.2986 - val_accuracy: 0.0685 - val_loss: 10.2046
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7037 - loss: 1.2898 - val_accuracy: 0.0705 - val_loss: 10.2996
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7057 - loss: 1.2780 - val_accuracy: 0.0708 - val_loss: 10.2926
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7090 - loss: 1.2649 - val_accuracy: 0.0719 - val_loss: 10.3471
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7101 - loss: 1.2583 - val_accuracy: 0.0689 - val_loss: 10.4260
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7106 - loss: 1.2564 - val_accuracy: 0.0702 - val_loss: 10.4203
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7115 - loss: 1.2496 - val_accuracy: 0.0716 - val_loss: 10.4870
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7147 - loss: 1.2319 - val_accuracy: 0.0682 - val_loss: 10.5156
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7177 - loss: 1.2187 - val_accuracy: 0.0698 - val_loss: 10.5753
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7179 - loss: 1.2185 - val_accuracy: 0.0694 - val_loss: 10.5704
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7197 - loss: 1.2078 - val_accuracy: 0.0682 - val_loss: 10.6623
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7225 - loss: 1.1959 - val_accuracy: 0.0713 - val_loss: 10.6893
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7241 - loss: 1.1869 - val_accuracy: 0.0722 - val_loss: 10.7239
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7256 - loss: 1.1808 - val_accuracy: 0.0675 - val_loss: 10.7641
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7268 - loss: 1.1754 - val_accuracy: 0.0693 - val_loss: 10.7894
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7253 - loss: 1.1749 - val_accuracy: 0.0693 - val_loss: 10.8251
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7295 - loss: 1.1634 - val_accuracy: 0.0706 - val_loss: 10.8530
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7294 - loss: 1.1621 - val_accuracy: 0.0689 - val_loss: 10.9049
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7290 - loss: 1.1583 - val_accuracy: 0.0682 - val_loss: 10.9015
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7340 - loss: 1.1392 - val_accuracy: 0.0688 - val_loss: 10.9542
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7336 - loss: 1.1365 - val_accuracy: 0.0686 - val_loss: 10.9915
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7348 - loss: 1.1335 - val_accuracy: 0.0695 - val_loss: 11.0416
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7384 - loss: 1.1169 - val_accuracy: 0.0695 - val_loss: 11.0566
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7391 - loss: 1.1162 - val_accuracy: 0.0675 - val_loss: 11.0975
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.7372 - loss: 1.1160 - val_accuracy: 0.0693 - val_loss: 11.1322
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7421 - loss: 1.1017 - val_accuracy: 0.0695 - val_loss: 11.2069
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7445 - loss: 1.0863 - val_accuracy: 0.0682 - val_loss: 11.2036
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7436 - loss: 1.0913 - val_accuracy: 0.0681 - val_loss: 11.2476
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7424 - loss: 1.0926 - val_accuracy: 0.0666 - val_loss: 11.2932
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7449 - loss: 1.0871 - val_accuracy: 0.0672 - val_loss: 11.3338
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7434 - loss: 1.0802 - val_accuracy: 0.0660 - val_loss: 11.3283
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7477 - loss: 1.0707 - val_accuracy: 0.0680 - val_loss: 11.3717
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.7454 - loss: 1.0774 - val_accuracy: 0.0668 - val_loss: 11.4181

In [36]:
epochs= 100
batch_size =128
history_lstm= lstm_model.fit(
    X_padded, y_one_hot,
    batch_size=batch_size,
    epochs=epochs,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 52ms/step - accuracy: 0.0397 - loss: 6.7549 - val_accuracy: 0.0492 - val_loss: 6.6850
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.0597 - loss: 6.3060 - val_accuracy: 0.0687 - val_loss: 6.5236
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.0837 - loss: 6.0312 - val_accuracy: 0.0908 - val_loss: 6.4468
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1008 - loss: 5.8127 - val_accuracy: 0.0972 - val_loss: 6.4026
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1128 - loss: 5.6215 - val_accuracy: 0.1039 - val_loss: 6.3810
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1223 - loss: 5.4482 - val_accuracy: 0.1073 - val_loss: 6.3935
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1304 - loss: 5.2922 - val_accuracy: 0.1079 - val_loss: 6.4221
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1389 - loss: 5.1461 - val_accuracy: 0.1085 - val_loss: 6.4659
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1456 - loss: 5.0072 - val_accuracy: 0.1113 - val_loss: 6.5033
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1526 - loss: 4.8739 - val_accuracy: 0.1120 - val_loss: 6.5513
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1573 - loss: 4.7437 - val_accuracy: 0.1128 - val_loss: 6.5996
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1667 - loss: 4.6165 - val_accuracy: 0.1143 - val_loss: 6.6676
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1767 - loss: 4.4915 - val_accuracy: 0.1133 - val_loss: 6.7363
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1863 - loss: 4.3694 - val_accuracy: 0.1141 - val_loss: 6.7958
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1983 - loss: 4.2498 - val_accuracy: 0.1141 - val_loss: 6.8841
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2106 - loss: 4.1347 - val_accuracy: 0.1153 - val_loss: 6.9568
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2259 - loss: 4.0224 - val_accuracy: 0.1126 - val_loss: 7.0420
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2409 - loss: 3.9160 - val_accuracy: 0.1105 - val_loss: 7.1181
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2552 - loss: 3.8158 - val_accuracy: 0.1117 - val_loss: 7.2015
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2681 - loss: 3.7219 - val_accuracy: 0.1115 - val_loss: 7.2731
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2823 - loss: 3.6327 - val_accuracy: 0.1099 - val_loss: 7.3574
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2946 - loss: 3.5518 - val_accuracy: 0.1082 - val_loss: 7.4394
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3062 - loss: 3.4724 - val_accuracy: 0.1106 - val_loss: 7.5088
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3183 - loss: 3.3993 - val_accuracy: 0.1120 - val_loss: 7.5947
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3298 - loss: 3.3292 - val_accuracy: 0.1054 - val_loss: 7.6765
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3401 - loss: 3.2630 - val_accuracy: 0.1059 - val_loss: 7.7346
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3502 - loss: 3.1997 - val_accuracy: 0.1081 - val_loss: 7.8180
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3601 - loss: 3.1371 - val_accuracy: 0.1053 - val_loss: 7.9062
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3692 - loss: 3.0823 - val_accuracy: 0.1021 - val_loss: 7.9573
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3782 - loss: 3.0245 - val_accuracy: 0.1034 - val_loss: 8.0312
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3896 - loss: 2.9677 - val_accuracy: 0.1045 - val_loss: 8.0953
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3978 - loss: 2.9144 - val_accuracy: 0.1035 - val_loss: 8.1568
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4064 - loss: 2.8631 - val_accuracy: 0.1017 - val_loss: 8.2431
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4144 - loss: 2.8134 - val_accuracy: 0.1001 - val_loss: 8.2965
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4238 - loss: 2.7646 - val_accuracy: 0.1004 - val_loss: 8.3602
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4317 - loss: 2.7171 - val_accuracy: 0.1010 - val_loss: 8.4299
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4387 - loss: 2.6721 - val_accuracy: 0.0993 - val_loss: 8.5011
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4475 - loss: 2.6280 - val_accuracy: 0.1019 - val_loss: 8.5538
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4555 - loss: 2.5846 - val_accuracy: 0.0971 - val_loss: 8.6181
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4625 - loss: 2.5425 - val_accuracy: 0.0977 - val_loss: 8.6836
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4692 - loss: 2.5007 - val_accuracy: 0.0950 - val_loss: 8.7512
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4783 - loss: 2.4611 - val_accuracy: 0.0950 - val_loss: 8.8035
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4850 - loss: 2.4224 - val_accuracy: 0.0946 - val_loss: 8.8640
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4926 - loss: 2.3839 - val_accuracy: 0.0943 - val_loss: 8.9314
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4978 - loss: 2.3468 - val_accuracy: 0.0945 - val_loss: 8.9733
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5061 - loss: 2.3119 - val_accuracy: 0.0942 - val_loss: 9.0450
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5112 - loss: 2.2766 - val_accuracy: 0.0926 - val_loss: 9.1005
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5192 - loss: 2.2418 - val_accuracy: 0.0920 - val_loss: 9.1676
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5258 - loss: 2.2084 - val_accuracy: 0.0911 - val_loss: 9.2177
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5316 - loss: 2.1764 - val_accuracy: 0.0888 - val_loss: 9.2874
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5373 - loss: 2.1434 - val_accuracy: 0.0884 - val_loss: 9.3429
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5449 - loss: 2.1133 - val_accuracy: 0.0876 - val_loss: 9.3959
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5498 - loss: 2.0828 - val_accuracy: 0.0867 - val_loss: 9.4536
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5561 - loss: 2.0543 - val_accuracy: 0.0843 - val_loss: 9.5204
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5607 - loss: 2.0239 - val_accuracy: 0.0882 - val_loss: 9.5578
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5681 - loss: 1.9976 - val_accuracy: 0.0892 - val_loss: 9.6291
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5742 - loss: 1.9683 - val_accuracy: 0.0875 - val_loss: 9.6718
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5788 - loss: 1.9421 - val_accuracy: 0.0862 - val_loss: 9.7367
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5844 - loss: 1.9164 - val_accuracy: 0.0858 - val_loss: 9.7870
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5903 - loss: 1.8907 - val_accuracy: 0.0840 - val_loss: 9.8349
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5939 - loss: 1.8653 - val_accuracy: 0.0830 - val_loss: 9.8939
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5994 - loss: 1.8417 - val_accuracy: 0.0844 - val_loss: 9.9621
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6046 - loss: 1.8169 - val_accuracy: 0.0790 - val_loss: 10.0009
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6099 - loss: 1.7936 - val_accuracy: 0.0851 - val_loss: 10.0657
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6143 - loss: 1.7709 - val_accuracy: 0.0826 - val_loss: 10.1050
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6174 - loss: 1.7490 - val_accuracy: 0.0824 - val_loss: 10.1779
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6227 - loss: 1.7276 - val_accuracy: 0.0797 - val_loss: 10.2240
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6271 - loss: 1.7055 - val_accuracy: 0.0827 - val_loss: 10.2840
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6311 - loss: 1.6859 - val_accuracy: 0.0822 - val_loss: 10.3229
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6357 - loss: 1.6645 - val_accuracy: 0.0814 - val_loss: 10.3757
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6402 - loss: 1.6441 - val_accuracy: 0.0820 - val_loss: 10.4303
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6451 - loss: 1.6242 - val_accuracy: 0.0801 - val_loss: 10.4788
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6474 - loss: 1.6058 - val_accuracy: 0.0810 - val_loss: 10.5362
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6521 - loss: 1.5860 - val_accuracy: 0.0804 - val_loss: 10.5911
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6570 - loss: 1.5682 - val_accuracy: 0.0800 - val_loss: 10.6460
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6605 - loss: 1.5490 - val_accuracy: 0.0801 - val_loss: 10.6721
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6640 - loss: 1.5311 - val_accuracy: 0.0781 - val_loss: 10.7221
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6678 - loss: 1.5135 - val_accuracy: 0.0776 - val_loss: 10.7705
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6720 - loss: 1.4979 - val_accuracy: 0.0777 - val_loss: 10.8444
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6756 - loss: 1.4801 - val_accuracy: 0.0776 - val_loss: 10.8752
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6785 - loss: 1.4640 - val_accuracy: 0.0772 - val_loss: 10.9205
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6826 - loss: 1.4459 - val_accuracy: 0.0792 - val_loss: 11.0009
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6855 - loss: 1.4303 - val_accuracy: 0.0803 - val_loss: 11.0139
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6894 - loss: 1.4161 - val_accuracy: 0.0775 - val_loss: 11.0738
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6917 - loss: 1.4007 - val_accuracy: 0.0777 - val_loss: 11.1290
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6962 - loss: 1.3841 - val_accuracy: 0.0766 - val_loss: 11.1618
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6983 - loss: 1.3703 - val_accuracy: 0.0758 - val_loss: 11.1961
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7030 - loss: 1.3558 - val_accuracy: 0.0768 - val_loss: 11.2694
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7047 - loss: 1.3411 - val_accuracy: 0.0763 - val_loss: 11.2955
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7077 - loss: 1.3263 - val_accuracy: 0.0797 - val_loss: 11.3668
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7087 - loss: 1.3276 - val_accuracy: 0.0782 - val_loss: 11.4320
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.7096 - loss: 1.3296 - val_accuracy: 0.0788 - val_loss: 11.4567
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7158 - loss: 1.2925 - val_accuracy: 0.0773 - val_loss: 11.4985
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7193 - loss: 1.2757 - val_accuracy: 0.0772 - val_loss: 11.5586
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 52ms/step - accuracy: 0.7222 - loss: 1.2607 - val_accuracy: 0.0760 - val_loss: 11.5992
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.7243 - loss: 1.2493 - val_accuracy: 0.0774 - val_loss: 11.6290
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7279 - loss: 1.2373 - val_accuracy: 0.0765 - val_loss: 11.6934
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7311 - loss: 1.2240 - val_accuracy: 0.0775 - val_loss: 11.7207
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7317 - loss: 1.2134 - val_accuracy: 0.0747 - val_loss: 11.7599
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7358 - loss: 1.2012 - val_accuracy: 0.0750 - val_loss: 11.8207

# GRU Model

In [40]:
gru_model = Sequential()
gru_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
gru_model.add(GRU(units=rnn_units))
gru_model.add(Dense(units=vocab_size, activation='softmax'))

In [41]:
gru_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [42]:
gru_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
epochs= 100
batch_size =128
gru_model.fit(
    X_padded, y_one_hot,
    batch_size=batch_size,
    epochs=epochs,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 49ms/step - accuracy: 0.0422 - loss: 6.7872 - val_accuracy: 0.0611 - val_loss: 6.5403
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.0805 - loss: 6.0860 - val_accuracy: 0.0923 - val_loss: 6.3256
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.1041 - loss: 5.7348 - val_accuracy: 0.1042 - val_loss: 6.2676
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.1203 - loss: 5.4395 - val_accuracy: 0.1123 - val_loss: 6.2885
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.1381 - loss: 5.1743 - val_accuracy: 0.1174 - val_loss: 6.3160
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.1517 - loss: 4.9297 - val_accuracy: 0.1188 - val_loss: 6.3543
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.1637 - loss: 4.7046 - val_accuracy: 0.1215 - val_loss: 6.4392
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.1791 - loss: 4.4947 - val_accuracy: 0.1224 - val_loss: 6.4998
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.1969 - loss: 4.2981 - val_accuracy: 0.1201 - val_loss: 6.5724
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.2185 - loss: 4.1123 - val_accuracy: 0.1231 - val_loss: 6.6482
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.2406 - loss: 3.9385 - val_accuracy: 0.1216 - val_loss: 6.7082
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.2636 - loss: 3.7762 - val_accuracy: 0.1157 - val_loss: 6.7780
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.2852 - loss: 3.6271 - val_accuracy: 0.1146 - val_loss: 6.8580
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.3053 - loss: 3.4898 - val_accuracy: 0.1156 - val_loss: 6.9180
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.3254 - loss: 3.3627 - val_accuracy: 0.1139 - val_loss: 6.9866
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.3443 - loss: 3.2451 - val_accuracy: 0.1137 - val_loss: 7.0560
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.3611 - loss: 3.1374 - val_accuracy: 0.1083 - val_loss: 7.1253
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 49ms/step - accuracy: 0.3787 - loss: 3.0363 - val_accuracy: 0.1073 - val_loss: 7.2019
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.3942 - loss: 2.9398 - val_accuracy: 0.1072 - val_loss: 7.2539
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.4087 - loss: 2.8532 - val_accuracy: 0.1066 - val_loss: 7.3232
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4229 - loss: 2.7701 - val_accuracy: 0.1041 - val_loss: 7.3930
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.4365 - loss: 2.6927 - val_accuracy: 0.1038 - val_loss: 7.4480
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.4484 - loss: 2.6188 - val_accuracy: 0.1038 - val_loss: 7.5188
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.4591 - loss: 2.5506 - val_accuracy: 0.0979 - val_loss: 7.5911
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4733 - loss: 2.4830 - val_accuracy: 0.1035 - val_loss: 7.6497
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.4835 - loss: 2.4225 - val_accuracy: 0.1017 - val_loss: 7.7078
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.4948 - loss: 2.3625 - val_accuracy: 0.0993 - val_loss: 7.7758
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.5048 - loss: 2.3086 - val_accuracy: 0.1012 - val_loss: 7.8366
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.5137 - loss: 2.2547 - val_accuracy: 0.0957 - val_loss: 7.8944
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.5248 - loss: 2.2047 - val_accuracy: 0.0970 - val_loss: 7.9669
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.5334 - loss: 2.1572 - val_accuracy: 0.0940 - val_loss: 8.0283
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.5412 - loss: 2.1115 - val_accuracy: 0.0937 - val_loss: 8.0944
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.5501 - loss: 2.0681 - val_accuracy: 0.0924 - val_loss: 8.1575
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.5572 - loss: 2.0263 - val_accuracy: 0.0939 - val_loss: 8.2174
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.5651 - loss: 1.9871 - val_accuracy: 0.0897 - val_loss: 8.2931
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.5723 - loss: 1.9498 - val_accuracy: 0.0899 - val_loss: 8.3310
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 49ms/step - accuracy: 0.5804 - loss: 1.9125 - val_accuracy: 0.0920 - val_loss: 8.4004
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.5876 - loss: 1.8797 - val_accuracy: 0.0874 - val_loss: 8.4638
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.5927 - loss: 1.8455 - val_accuracy: 0.0852 - val_loss: 8.5194
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.5984 - loss: 1.8126 - val_accuracy: 0.0870 - val_loss: 8.5854
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6047 - loss: 1.7829 - val_accuracy: 0.0888 - val_loss: 8.6457
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6093 - loss: 1.7540 - val_accuracy: 0.0848 - val_loss: 8.6880
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.6165 - loss: 1.7245 - val_accuracy: 0.0869 - val_loss: 8.7355
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.6208 - loss: 1.6976 - val_accuracy: 0.0857 - val_loss: 8.8099
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6266 - loss: 1.6741 - val_accuracy: 0.0878 - val_loss: 8.8610
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.6321 - loss: 1.6472 - val_accuracy: 0.0847 - val_loss: 8.9290
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.6361 - loss: 1.6283 - val_accuracy: 0.0845 - val_loss: 8.9682
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.6398 - loss: 1.6029 - val_accuracy: 0.0833 - val_loss: 9.0206
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.6449 - loss: 1.5793 - val_accuracy: 0.0820 - val_loss: 9.0700
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.6515 - loss: 1.5563 - val_accuracy: 0.0838 - val_loss: 9.1369
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 49ms/step - accuracy: 0.6551 - loss: 1.5355 - val_accuracy: 0.0830 - val_loss: 9.1764
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.6581 - loss: 1.5184 - val_accuracy: 0.0834 - val_loss: 9.2317
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.6599 - loss: 1.5037 - val_accuracy: 0.0822 - val_loss: 9.2943
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 49ms/step - accuracy: 0.6642 - loss: 1.4840 - val_accuracy: 0.0824 - val_loss: 9.3396
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.6695 - loss: 1.4611 - val_accuracy: 0.0845 - val_loss: 9.4181
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.6721 - loss: 1.4458 - val_accuracy: 0.0822 - val_loss: 9.4497
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.6767 - loss: 1.4323 - val_accuracy: 0.0821 - val_loss: 9.5080
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.6779 - loss: 1.4158 - val_accuracy: 0.0813 - val_loss: 9.5696
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6828 - loss: 1.3998 - val_accuracy: 0.0829 - val_loss: 9.6099
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.6851 - loss: 1.3843 - val_accuracy: 0.0804 - val_loss: 9.6785
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.6903 - loss: 1.3647 - val_accuracy: 0.0809 - val_loss: 9.7094
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.6920 - loss: 1.3535 - val_accuracy: 0.0817 - val_loss: 9.7675
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.6964 - loss: 1.3401 - val_accuracy: 0.0816 - val_loss: 9.8154
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.6975 - loss: 1.3250 - val_accuracy: 0.0817 - val_loss: 9.8703
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7020 - loss: 1.3125 - val_accuracy: 0.0789 - val_loss: 9.9092
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7017 - loss: 1.3018 - val_accuracy: 0.0770 - val_loss: 9.9596
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7063 - loss: 1.2887 - val_accuracy: 0.0803 - val_loss: 10.0039
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7082 - loss: 1.2759 - val_accuracy: 0.0790 - val_loss: 10.0688
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7113 - loss: 1.2618 - val_accuracy: 0.0803 - val_loss: 10.1203
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7129 - loss: 1.2512 - val_accuracy: 0.0834 - val_loss: 10.1664
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7155 - loss: 1.2397 - val_accuracy: 0.0781 - val_loss: 10.2105
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7190 - loss: 1.2258 - val_accuracy: 0.0754 - val_loss: 10.2646
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7190 - loss: 1.2178 - val_accuracy: 0.0801 - val_loss: 10.2988
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7214 - loss: 1.2139 - val_accuracy: 0.0747 - val_loss: 10.3436
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7238 - loss: 1.2007 - val_accuracy: 0.0749 - val_loss: 10.3974
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.7253 - loss: 1.1912 - val_accuracy: 0.0776 - val_loss: 10.4402
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.7265 - loss: 1.1830 - val_accuracy: 0.0749 - val_loss: 10.4465
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.7296 - loss: 1.1711 - val_accuracy: 0.0767 - val_loss: 10.5189
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.7324 - loss: 1.1603 - val_accuracy: 0.0780 - val_loss: 10.5690
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7327 - loss: 1.1564 - val_accuracy: 0.0756 - val_loss: 10.5892
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7324 - loss: 1.1506 - val_accuracy: 0.0767 - val_loss: 10.6724
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7349 - loss: 1.1413 - val_accuracy: 0.0774 - val_loss: 10.6843
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7370 - loss: 1.1307 - val_accuracy: 0.0788 - val_loss: 10.6979
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7400 - loss: 1.1201 - val_accuracy: 0.0749 - val_loss: 10.7409
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7434 - loss: 1.1086 - val_accuracy: 0.0738 - val_loss: 10.8243
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7432 - loss: 1.1023 - val_accuracy: 0.0752 - val_loss: 10.8271
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7474 - loss: 1.0903 - val_accuracy: 0.0773 - val_loss: 10.8998
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.7459 - loss: 1.0912 - val_accuracy: 0.0745 - val_loss: 10.9299
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.7486 - loss: 1.0846 - val_accuracy: 0.0748 - val_loss: 10.9474
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7475 - loss: 1.0813 - val_accuracy: 0.0745 - val_loss: 10.9769
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7490 - loss: 1.0770 - val_accuracy: 0.0747 - val_loss: 11.0139
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7491 - loss: 1.0699 - val_accuracy: 0.0750 - val_loss: 11.0887
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7549 - loss: 1.0501 - val_accuracy: 0.0742 - val_loss: 11.1531
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7573 - loss: 1.0418 - val_accuracy: 0.0741 - val_loss: 11.1422
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7565 - loss: 1.0407 - val_accuracy: 0.0727 - val_loss: 11.1700
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7588 - loss: 1.0290 - val_accuracy: 0.0720 - val_loss: 11.2210
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7563 - loss: 1.0364 - val_accuracy: 0.0747 - val_loss: 11.2837
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7623 - loss: 1.0195 - val_accuracy: 0.0726 - val_loss: 11.2956
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7643 - loss: 1.0073 - val_accuracy: 0.0745 - val_loss: 11.3014
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.7620 - loss: 1.0125 - val_accuracy: 0.0738 - val_loss: 11.3598

In [46]:
lstm_model.save("lstm_model.h5")
rnn_model.save("rnn_model.h5")
gru_model.save("gru_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [60]:
from tensorflow.keras.models import load_model
lstm_model = load_model("lstm_model.h5")
rnn_model = load_model("rnn_model.h5")
gru_model = load_model("gru_model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [48]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [49]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [50]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [51]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

thought

In [52]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [55]:
seed = "are you a "
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,10)
print(generate_text)

are you a  shelf beat beat spans spans filthy filthy redeemednever professions fastly

In [65]:
seed_text = "what are you"

# RNN prediction
rnn_prediction = predictor(
    rnn_model, tokinizer, seed_text, max_len
)

# LSTM prediction
lstm_prediction = predictor(
    lstm_model, tokinizer, seed_text, max_len
)

# GRU prediction
gru_prediction = predictor(
    gru_model, tokinizer, seed_text, max_len
)

print("Input Text:", seed_text)
print("-" * 35)
print("RNN Prediction:", rnn_prediction)
print("LSTM Prediction:", lstm_prediction)
print("GRU Prediction:", gru_prediction)

Input Text: what are you
-----------------------------------
RNN Prediction: nap
LSTM Prediction: whose
GRU Prediction: know

In [66]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokinizer, f)

In [67]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)